[package]
name = "bun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typenum = "1.16.0"
typ = { path = "../typ" }
paste = "1.0"

[dependencies.bun-macros]
path = "bun-macros"
